name: Build and Run Hello World Porject

on:
   workflow_dispatch:

jobs:
  bump-patch-version:
    runs-on: ubuntu-latest
    outputs:
      new_version_id: ${{ steps.version.outputs.new_version_id }} 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup prerequisites 
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Bump patch version
      id: version
      run: |
          source wf-functions.sh
          chmod +x wf-functions.sh

          cd myapp
          output=$(incrementVersion)
          echo "new_version_id=$output" >> $GITHUB_ENV
          echo "new_version_id=$output" >> $GITHUB_OUTPUT

    - name: Commit version bump
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add myapp/pom.xml
        git commit -m "Bump version to $new_version_id"
        git push
          
  docker-build-and-run:
     runs-on: ubuntu-latest
     needs: bump-patch-version
     steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate into Docker registery service
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
            source wf-functions.sh
            BuildAndPushDockerImage --new_version_id "${{ needs.bump-patch-version.outputs.new_version_id }}" --registery_username "${{ secrets.DOCKER_USERNAME }}"

      - name: Pull image and run app
        run: |
            source wf-functions.sh
            PullImageAndRun  --new_version_id "${{ needs.bump-patch-version.outputs.new_version_id }}" --registery_username "${{ secrets.DOCKER_USERNAME }}"